### ISSUE TITLE
Design a persistence store for the aggregate data about videos

### ISSUE THREAD

**Issue by abessou** [abessou/w251-FinalProject#13]
The store should be able to store:
For Facebook videos: video Id, likes count, views count
For Twitter videos: video Id, retweets count
For Youtube videos: Views, Likes, Dislikes
Please check with people working on the data sources for specifics.

The aggregates do not need to be stored in the same table for all sources. They can if that's practical.

We need a script to create the database in Postgres and create the tables required.
Ideally, the data sources can make use of a simple Python library to create/update new aggregate counts for new videos they have processed without having to know about the organization of the storage. The library API should isolate them from the storage.

There should be a setup script that installs all that's required for this library (juts a list of bash commands, including pip install commands for required packages).

**Comment by venamax** [comment]
Charles,

Take a look at the Postgres code here...You can adapt to include all
sources...Right now only includes Twitter

https://github.com/W205-Social-Media/w205-data-ingest/blob/develop/PostgresDataIngestSink.py

**Comment by andrea-soto** [comment]
Used Mongo
