### ISSUE TITLE
Update frequency for counts (likes, comments, retweets, ets)

### ISSUE THREAD

**Issue by andrea-soto** [abessou/w251-FinalProject#23]
Decide how often we are going to update the counts and which videos we will update (all? a subset?)

**Comment by mjasek114** [comment]
For Twitter, the streaming code that we currently have is always updating counts of previously created tweets.  Currently, there is no code and I don't know how to go out to the Twitter database and query it for current counts of Tweets.  I'm guessing there is a way to do this though, but I haven't explored it.
